name: New Solar System Workflow


on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        services:
          mongodb:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password        
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20

        - name: Cache NPM dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodejs-unit-testing-step
          run: npm test
          
        - name: Archive Test Result
        # the line below is commeneted as we've added an alternative: always
        #   if: failure() && (steps.nodejs-unit-testing-step.outcome == 'failure' || steps.nodejs-unit-testing-step.outcome == 'success')
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
        name: Code Coverage
        needs: unit-testing
        runs-on: ubuntu-latest
        container:
          image: node:20
        services:
          mongodb:
            image: siddharth67/mongo-db:non-prod
            options:
              --name mongo
        env:
          MONGO_URI: 'mongodb://mongo:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password     
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        # We comment the lines below due to having Job Container
        # - name: Setup NodeJS Version
        #   uses: actions/setup-node@v3
        #   with:
        #     node-version: 20

        - name: Cache NPM dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}            
 
        - name: Install Dependencies
          run: npm install
    
        - name: Check Code Coverage
          continue-on-error: true
          run: npm run coverage
          
        - name: Archive Code Coverage Result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result
            path: coverage
            retention_days: 5

    reports-s3:
      name: AWS S3 - Upload Reports
      needs: [code-coverage, unit-testing]
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - name: Download Mocha Test Artifact
          uses: actions/download-artifact@v4
          with:
            name: Mocha-Test-Result

        - name: Download Code Coverage Artifact
          uses: actions/download-artifact@v4
          with:
            name: Code-Coverage-Result
        
        - name: Merge Test Files
          run: |
            ls -lrt
            mkdir reports-${{ github.sha }}
            mv test-results.xml reports-${{ github.sha }}/
            mv cobertura-coverage.xml reports-${{ github.sha }}/
            ls -lrt reports-${{ github.sha }}/
        
        - name: Upload to AWS S3
          uses: jakejarvis/s3-sync-action@master
          with:
            args: --acl public-read --follow-symlinks --delete
          env:
            AWS_S3_BUCKET: solar-system-reports-bucket
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: 'us-east-1'
            SOURCE_DIR: 'reports-${{ github.sha }}'
            DEST_DIR: 'reports-${{ github.sha }}'

    docker:
        name: Containerization
        needs: [unit-testing, code-coverage]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Dockerhub Login
          uses: docker/login-action@v3.4.0
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Docker Build For Testing
          uses: docker/build-push-action@v6
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
        
        - name: Docker Image Testing
          run: |
            docker images
            docker run --name solar-system-app -d \
            -p 3000:3000 \
            -e MONGO_URI:$MONGO_URI \
            -e MONGO_USERNAME:$MONGO_USERNAME \
            -e MONGO_PASSWORD:$MONGO_PASSWORD \
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo $IP

            echo Testing Image URL using wget
            wget -q -O - 127.0.0.1:3000/live | grep live
        
        - name: Docker Push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}            
     
    dev-deploy:
        name: Dev Deployment
        if: contains(github.ref, 'feature/')
        needs: docker
        uses: ./.github/workflows/reuse-deployment.yml
        secrets:
          k8s-kubeconfig: ${{ secrets.KUBECONFIG }}
          mongodb-password: ${{ secrets.MONGO_PASSWORDS }}
        with:
          mongodb-uri: ${{ vars.MONGO_URI }}
          environment: development
          k8s-manifest-dir: kubernetes/development/
          kubectl-version: v1.26.0

    dev-integration-testing:
        name: Dev Integration Testing
        if: contains(github.ref, 'feature/')
        needs: dev-deploy
        runs-on: ubuntu-latest
        steps:
        - name: Test URl Output using CURL and JQ
          continue-on-error: true        
          env:
            URL: ${{ needs.dev-deploy.outputs.application-url }}
          run: |
            echo $URL
            echo "-------------------------------"
            curl https://$URL/live -s -k | jq -r .status | grep -i live

    prod-deploy:
        name: Prod Deployment
        if: github.ref == 'refs/heads/main'
        needs: docker
        uses: ./.github/workflows/reuse-deployment.yml
        secrets:
          k8s-kubeconfig: ${{ secrets.KUBECONFIG }}
          mongodb-password: ${{ secrets.MONGO_PASSWORDS }}        
        with:
          mongodb-uri: ${{ vars.MONGO_URI }}
          environment: production          
          k8s-manifest-dir: kubernetes/production/
          kubectl-version: v1.26.0          

    prod-integration-testing:
        name: prod Integration Testing
        if: github.ref == 'refs/heads/main'
        needs: prod-deploy
        runs-on: ubuntu-latest
        steps:
        - name: Test URl Output using CURL and JQ
          continue-on-error: true        
          env:
            URL: ${{ needs.prod-deploy.outputs.application-url }}
          run: |
            echo $URL
            echo "-------------------------------"
            curl https://$URL/live -s -k | jq -r .status | grep -i live